language: go

sudo: false

go:
  - 1.5

before_install:
  - go get -u github.com/cep21/goverify
  - go get github.com/mattn/goveralls

install:
  - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host git.apache.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - go get -d -v -t ./... 

script:
  - export PATH=$HOME/gopath/bin:$PATH
  - export GOCOVERDIR_DIR="."
  - goverify -v
  - goveralls -coverprofile=coverage.out -service=travis-ci

after_script:
  - cat coverage.out

