[vars]
  duplLimit = "300"
  testCoverage = 100.0

[metalinter]
  [metalinter.enabled]
    golint = true
    gofmt = true
    varcheck = true
    aligncheck = true
    gocyclo = true
    vet = true
    deadcode = true

