[vars]
  duplLimit = "300"
  testCoverage = 100.0

[metalinter]
  [metalinter.ignored]
    go14= "^.*has no field or method Cancel.*$" 
    logargs = "no args in Log call"
  [metalinter.enabled]
    golint = true
    gofmt = true
    varcheck = true
    aligncheck = true
    gocyclo = true
    vet = true
    deadcode = true
